import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(process.env.PLAYWRIGHT_PACKAGE || import.meta.url);
const { chromium } = require('playwright');
const browser = await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL || 'chrome'});
const page = await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.goto(process.env.APP_URL || 'http://127.0.0.1:4175');
await page.locator('#salary').fill('8000');
await page.locator('#salary').dispatchEvent('input');
await page.waitForTimeout(200);
assert.match(await page.locator('#annual-income').textContent(),/96,000/);
assert.match(await page.locator('#tax-value').textContent(),/3,156/);
await page.getByRole('button',{name:'Annual',exact:true}).click();
assert.equal(await page.locator('#salary').inputValue(),'96000');
assert.match(await page.locator('#computation-lines').textContent(),/3,156.80/);
assert.match(await page.locator('#tax-value').textContent(),/3,156/);
await page.getByRole('button',{name:'Detailed estimate',exact:true}).click();
assert.equal(await page.locator('details:not([open])').count(),0);
await page.locator('#srs').fill('3000');
assert.match(await page.locator('#tax-value').textContent(),/2,946/);
await page.getByRole('button',{name:'Save estimate',exact:true}).click();
await page.getByRole('link',{name:'Compare scenarios'}).click();
assert.equal(await page.locator('.scenario').count(),3);
await page.locator('#srs-extra').fill('2000');
await page.locator('#apply-srs').click();
assert.equal(await page.locator('#srs').inputValue(),'5000');
assert.match(await page.locator('#tax-value').textContent(),/2,806/);
await page.getByRole('button',{name:'Quick estimate',exact:true}).click();
assert.equal(await page.locator('details[open]').count(),0);
assert.match(await page.locator('#tax-value').textContent(),/2,806/);
await page.getByRole('button',{name:'Reset estimate',exact:true}).click();
assert.match(await page.locator('#tax-value').textContent(),/1,040/);
await page.getByRole('link',{name:'Compare scenarios'}).click();
await page.locator('#load-saved').click();
assert.equal(await page.locator('#srs').inputValue(),'3000');
assert.equal(await page.locator('#salary').inputValue(),'96000');
const download = page.waitForEvent('download');
await page.locator('#export').click();
assert.match((await download).suggestedFilename(),/iras-helper.*csv/);
await page.evaluate(()=>window.scrollTo(0,0));
await page.screenshot({path:'/tmp/iras-helper-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/iras-helper-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
await page.getByRole('link',{name:'Tax guide',exact:true}).click();
await page.locator('#page-guide').waitFor({state:'visible'});
assert.equal(await page.locator('#page-guide').isVisible(),true);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
await page.getByRole('link',{name:'Tax estimator',exact:true}).click();
await page.locator('#page-estimate').waitFor({state:'visible'});
await page.locator('#salary').fill('-1');
assert.equal(await page.locator('#validation-errors').isVisible(),true);
assert.match(await page.locator('#tax-value').textContent(),/2,946.80/);
await page.locator('#salary').fill('96000');
assert.equal(await page.locator('#validation-errors').isVisible(),false);
await page.locator('#year').selectOption('2027');
assert.match(await page.locator('#projection-label').textContent(),/projection/);
await page.getByRole('button',{name:'Detailed estimate',exact:true}).click();
await page.locator('#citizenship').selectOption('foreigner');
assert.equal(await page.locator('#cpfMode').isDisabled(),true);
await page.getByRole('button',{name:'Quick estimate',exact:true}).click();
for(const width of [360,768,1024]){
  await page.setViewportSize({width,height:900});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,`layout fits at ${width}px`);
}
await page.getByRole('button',{name:'Reset estimate',exact:true}).click();
await page.locator('#salary').fill('4999.99');
await page.getByRole('link',{name:'Compare scenarios'}).click();
await page.locator('#page-compare').waitFor({state:'visible'});
assert.match(await page.locator('.scenario.current').textContent(),/1,040.77/);
assert.deepEqual(errors,[]);
await browser.close();
console.log('Browser checks passed: estimate, details, periods, scenarios, save/restore, export, routing, mobile layout; no page errors.');
